export type BookEntity = {
  id: string;
  name: string;
  kind: "Pessoa" | "Lugar";
  aliases: string[];
  summary: string;
  chapters: number[];
};

export const BOOK_ENTITIES: BookEntity[] = [
  {
    id: "soren-vale",
    name: "Soren Vale",
    kind: "Pessoa",
    aliases: ["Soren Vale", "Soren", "Historiador Vale", "Professor Vale"],
    summary: "Historiador dos Arquivos Centrais. Investiga como decisões, responsabilidade e memória foram transferidas para sistemas preditivos.",
    chapters: [1, 2, 3, 4, 6, 7],
  },
  {
    id: "naia-vey",
    name: "Naia Vey",
    kind: "Pessoa",
    aliases: ["Naia Vey", "Naia"],
    summary: "Curadora rigorosa que transforma valores políticos em critérios auditáveis. Sua amizade intelectual com Soren atravessa décadas.",
    chapters: [2, 3, 4],
  },
  {
    id: "tarek-venn",
    name: "Tarek Venn",
    kind: "Pessoa",
    aliases: ["Tarek Venn", "Tarek"],
    summary: "Jovem oficial da Frota de Coordenação. Em Pelagos, aprende quanto pode custar a liberdade de contrariar uma previsão.",
    chapters: [5, 6],
  },
  {
    id: "cassian-dhor",
    name: "Cassian Dhor",
    kind: "Pessoa",
    aliases: ["Cassian Dhor", "Cassian", "Delegado Dhor"],
    summary: "Delegado de Qelven. Defende as reservas do mundo contra uma seca futura possível e exige que a incerteza também seja considerada.",
    chapters: [1],
  },
  {
    id: "edrin-sol",
    name: "Edrin Sol",
    kind: "Pessoa",
    aliases: ["Edrin Sol", "Edrin"],
    summary: "Condutor da sessão do Conselho sobre a crise agrícola. Encaminha a Consulta Integrada e organiza a comparação das propostas.",
    chapters: [1],
  },
  {
    id: "mael-tura",
    name: "Mael Tura",
    kind: "Pessoa",
    aliases: ["Mael Tura", "Mael"],
    summary: "Representante de Ilyr. Protege a autonomia industrial de seu mundo e questiona quando uma emergência vira poder permanente.",
    chapters: [1],
  },
  {
    id: "serai-kelm",
    name: "Serai Kelm",
    kind: "Pessoa",
    aliases: ["Serai Kelm", "Serai"],
    summary: "Curadora de sessão responsável por apresentar e integrar os cenários compostos durante a crise agrícola.",
    chapters: [1],
  },
  {
    id: "tala-orin",
    name: "Tala Orin",
    kind: "Pessoa",
    aliases: ["Tala Orin", "Tala", "Delegada Orin"],
    summary: "Delegada de Maraith. Defende ajuda imediata para uma população já submetida a racionamento e perda de colheitas.",
    chapters: [1],
  },
  {
    id: "dara-kett",
    name: "Dara Kett",
    kind: "Pessoa",
    aliases: ["Dara Kett", "Dara"],
    summary: "Participante da revisão que contesta o rebaixamento da expansão de Neryn e força Naia a explicitar quem arca com cada escolha.",
    chapters: [2],
  },
  {
    id: "iven-saar",
    name: "Iven Saar",
    kind: "Pessoa",
    aliases: ["Iven Saar", "Iven"],
    summary: "Curador e interlocutor veterano de Naia. Ajuda a transformar responsabilidade difusa em uma cadeia de contribuições identificáveis.",
    chapters: [2, 4],
  },
  {
    id: "selka-ren",
    name: "Selka Ren",
    kind: "Pessoa",
    aliases: ["Selka Ren", "Selka"],
    summary: "Integrante da equipe de validação e certificação que trabalha com Naia na formalização das responsabilidades técnicas.",
    chapters: [2],
  },
  {
    id: "amon-taris",
    name: "Amon Taris",
    kind: "Pessoa",
    aliases: ["General Amon Taris", "Amon Taris", "Taris"],
    summary: "General e governador militar de Oros. Sua decisão histórica oferece a Soren um estudo sobre certeza, retrospectiva e erro humano.",
    chapters: [3],
  },
  {
    id: "lem-var",
    name: "Lem Var",
    kind: "Pessoa",
    aliases: ["Lem Var"],
    summary: "Assessor de Amon Taris que apresentou um plano de retirada usado depois nas reconstruções contrafactuais de Soren.",
    chapters: [3],
  },
  {
    id: "oren-sahl",
    name: "Oren Sahl",
    kind: "Pessoa",
    aliases: ["Oren Sahl", "Oren"],
    summary: "Autoridade envolvida na pré-audiência sobre prioridades. Defende o padrão criado para afastar política da alocação técnica.",
    chapters: [4],
  },
  {
    id: "vessa-tor",
    name: "Vessa Tor",
    kind: "Pessoa",
    aliases: ["Vessa Tor", "Vessa"],
    summary: "Engenheira de sistemas que participa da definição dos critérios de certificação, rastreabilidade e responsabilidade.",
    chapters: [4],
  },
  {
    id: "darel-sen",
    name: "Darel Sen",
    kind: "Pessoa",
    aliases: ["Darel Sen", "Darel"],
    summary: "Administrador em Pelagos que recusa uma recomendação preventiva. Sua assinatura permanece no centro do debate sobre autonomia e custo.",
    chapters: [5, 6],
  },
  {
    id: "eryn-hal",
    name: "Eryn Hal",
    kind: "Pessoa",
    aliases: ["Comandante Eryn Hal", "Eryn Hal", "Comandante Hal", "Eryn"],
    summary: "Comandante da Frota que coordena a resposta operacional em Namar e defende antecipar a competência preventiva.",
    chapters: [5, 6],
  },
  {
    id: "mira-tal",
    name: "Mira Tal",
    kind: "Pessoa",
    aliases: ["Mira Tal", "Mira"],
    summary: "Supervisora de uma antiga plataforma de processamento. Traduz decisões de rota e prontidão em consequências operacionais concretas.",
    chapters: [5, 6],
  },
  {
    id: "lior-vask",
    name: "Lior Vask",
    kind: "Pessoa",
    aliases: ["Lior Vask", "Lior"],
    summary: "Administrador de Talassar que recebe o protocolo de preparação progressiva e questiona o significado prático de cada alerta.",
    chapters: [6],
  },
  {
    id: "lysa-an",
    name: "Lysa An",
    kind: "Pessoa",
    aliases: ["Lysa An"],
    summary: "Pesquisadora dos Arquivos na estação vizinha à de Soren. Ajuda a formular o problema de uma classificação que sobrevive por séculos.",
    chapters: [7],
  },
  {
    id: "elian-rho",
    name: "Elian Rho",
    kind: "Pessoa",
    aliases: ["Elian Rho", "Elian"],
    summary: "Especialista em preservação e manutenção de redes históricas. É chamado por Soren para rastrear a genealogia técnica de Butler.",
    chapters: [7],
  },
  {
    id: "butler",
    name: "Butler",
    kind: "Pessoa",
    aliases: ["Butler"],
    summary: "Nome de origem indeterminada ligado a uma antiga doutrina de autoria humana. As fontes divergem sobre ser pessoa, grupo ou rótulo posterior.",
    chapters: [7],
  },
  {
    id: "salusa-secundus",
    name: "Salusa Secundus",
    kind: "Lugar",
    aliases: ["Salusa Secundus", "Salusa"],
    summary: "Mundo que abriga os Arquivos Históricos Centrais, infraestrutura de Coordenação e sessões importantes do Conselho.",
    chapters: [1],
  },
  {
    id: "qelven",
    name: "Qelven",
    kind: "Lugar",
    aliases: ["Qelven"],
    summary: "Mundo produtor de grãos com grandes reservas, ameaçado por modelos climáticos divergentes sobre uma possível nova seca.",
    chapters: [1],
  },
  {
    id: "ilyr",
    name: "Ilyr",
    kind: "Lugar",
    aliases: ["Ilyr"],
    summary: "Mundo industrial capaz de converter linhas de produção para alimentos, mas ligado a cadeias de energia e componentes essenciais.",
    chapters: [1],
  },
  {
    id: "maraith",
    name: "Maraith",
    kind: "Lugar",
    aliases: ["Maraith"],
    summary: "Mundo atingido por duas colheitas ruins e racionamento, foco imediato da crise de distribuição do Conselho.",
    chapters: [1],
  },
  {
    id: "vespera",
    name: "Vespera",
    kind: "Lugar",
    aliases: ["Vespera"],
    summary: "Mundo de produção biomédica e grandes corredores logísticos. Seus componentes e sua capacidade de carga conectam crises distantes.",
    chapters: [1, 5],
  },
  {
    id: "parem",
    name: "Parem",
    kind: "Lugar",
    aliases: ["Parem"],
    summary: "Local afetado por isolamento prolongado, usado por Naia para testar se uma calibração esconde falhas de recuperação.",
    chapters: [2],
  },
  {
    id: "neryn",
    name: "Neryn",
    kind: "Lugar",
    aliases: ["Neryn"],
    summary: "Colônia ou sistema cuja expansão perde prioridade após a nova calibração, tornando visível quem paga pelo risco agregado.",
    chapters: [2],
  },
  {
    id: "oros",
    name: "Oros",
    kind: "Lugar",
    aliases: ["Oros"],
    summary: "Mundo governado militarmente por Amon Taris, palco de uma guerra reconstruída por Soren em modelos contrafactuais.",
    chapters: [3],
  },
  {
    id: "pelagos",
    name: "Pelagos",
    kind: "Lugar",
    aliases: ["Pelagos"],
    summary: "Mundo de plataformas e infraestrutura móvel onde uma recomendação preventiva é recusada e depois reavaliada.",
    chapters: [5, 6],
  },
  {
    id: "hadran",
    name: "Corredor de Hadran",
    kind: "Lugar",
    aliases: ["Corredor de Hadran", "Hadran"],
    summary: "Corredor de tráfego crítico em Pelagos. Fechá-lo cedo preservaria capacidade de evacuação, mas imporia custos imediatos.",
    chapters: [5, 6],
  },
  {
    id: "namar-quatro",
    name: "Namar Quatro",
    kind: "Lugar",
    aliases: ["Namar Quatro"],
    summary: "Plataforma ameaçada por falhas de ancoragem, centro da evacuação que transforma uma faixa de risco em decisões assinadas.",
    chapters: [5, 6],
  },
  {
    id: "namar-seis",
    name: "Namar Seis",
    kind: "Lugar",
    aliases: ["Namar Seis"],
    summary: "Outra plataforma do complexo de Namar, para onde parte dos meios da Frota é deslocada durante a emergência.",
    chapters: [5, 6],
  },
  {
    id: "talassar",
    name: "Talassar",
    kind: "Lugar",
    aliases: ["Talassar"],
    summary: "Local onde a preparação progressiva reduz risco sem exigir evacuação, oferecendo um contraponto ao desastre de Namar.",
    chapters: [6],
  },
];
